name: Build BLE Password Manager

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build firmware
        run: pio run

      - name: Show build folder content
        run: |
          echo "=== Папка .pio/build ==="
          ls -lR .pio/build || echo "Нет папки .pio/build"

      - name: Upload any .bin files
        uses: actions/upload-artifact@v4
        with:
          name: firmware-binaries
          path: '**/*.bin'
